package org.example.enums;

public enum EConversationStep {
    CITY_CHOICE,
    CITY_INPUT,
    BIRTHDAY_INPUT,
    CHILD_DOCUMENT,
    FULL_NAME_INPUT,
    GENDER_CHOICE,
    PHONE_INPUT,
    EDUCATION_STATUS_CHOICE,
    EDUCATION_INSTITUTION_CHOICE,
    EDUCATION_INSTITUTION_INPUT,
}
